adj1 = input('Please enter ADJECTIVE #1')
adj2 = input('Please enter ADJECTIVE #2')
adj3 = input('Please enter ADJECTIVE #3')
adj4 = input('Please enter ADJECTIVE #4')
adj5 = input('Please enter ADJECTIVE #5')
adverb = input('Please enter ADVERB #1')
noun1 = input('Please enter NOUN #1')
noun2 = input('Please enter NOUN #2')
noun3 = input('Please enter NOUN #3')
plural_noun4 = input('Please enter NOUN #4 - plural')
plural_noun5 = input('Please enter NOUN #5 - plural')
verb = input('Please enter VERB #1 - present tense infinite, e.g. walk, cook, read')


print("Here {}s the {}, here {}s the {}".format(verb, noun1, verb, noun1))
print("And I say it's all {}".format(adj1))
print("")
print("{} {}, it's been a {} {} {} winter".format(adj5, noun2, adj2, adj3, adj4))
print("{} {}, it feels like years since it's been here".format(adj5, noun2))
print("")
print("Here {}s the {}, here {}s the {}".format(verb, noun1, verb, noun1))
print("And I say it's all {}".format(adj1))
print("")
print("{} {}, the {} returning to the {}".format(adj5, noun2, plural_noun5, plural_noun4))
print("{} {}, it seems like years since it's been here".format(adj5, noun2))
print("")
print("Here {}s the {}, here {}s the {}".format(verb, noun1, verb, noun1))
print("And I say it's all {}".format(adj1))
print("")
print("{}, {}, {}, here it {}s".format(noun1, noun1, noun1, verb))
print("{}, {}, {}, here it {}s".format(noun1, noun1, noun1, verb))
print("{}, {}, {}, here it {}s".format(noun1, noun1, noun1, verb))
print("{}, {}, {}, here it {}s".format(noun1, noun1, noun1, verb))
print("{}, {}, {}, here it {}s".format(noun1, noun1, noun1, verb))
print("")
print("{} {}, I feel that {} is {} melting".format(adj5, noun2, noun3, adverb))
print("{} {}, it seems like years since it's been clear".format(adj5, noun2))
print("")
print("Here {}s the {}, here {}s the {}".format(verb, noun1, verb, noun1))
print("And I say it's all {}".format(adj1))
print("Here {}s the {}, here {}s the {}".format(verb, noun1, verb, noun1))
print("It's all {}, it's all {}".format(adj1, adj1))

